export { ChatWidget } from './components/ChatWidget'
export { ChatInput } from './components/ChatInput'
export { ChatWindow } from './components/ChatWindow'
export { ProductContextPreview } from './components/ProductContextPreview'
export { GuestIdentityForm } from './components/GuestIdentityForm'
export { useChat } from './hooks/useChat'
export { chatService } from './services/chat.service'
export { chatRepository } from './services/chat.repository'
export { BOT_REPLIES, BOT_REPLY_DELAY_MS, GUEST_ID_KEY, GUEST_PROFILE_KEY } from './constants/chat.constants'
export { guestProfileSchema } from './schemas/guest.schema'
export type { GuestProfileInput } from './schemas/guest.schema'
export type { ChatConversation, ChatIdentity, ChatMessage } from './types/chat.type'
