import type { Product } from '../types/product.type'
import { unsplashUrl as img } from '../../../shared/utils/unsplash'

const v = (id: string, name: string, delta: number, stock: number) => ({
  id,
  variant_name: name,
  price_delta: delta,
  stock,
})

const elecColors = ['Hitam', 'Putih', 'Silver', 'Navy', 'Merah']
const elecSizes = ['XS', 'S', 'M', 'L', 'XL']
const apparelColors = ['Merah', 'Hijau', 'Hitam', 'Putih', 'Biru']
const apparelSizes = ['XS', 'S', 'M', 'L', 'XL']
const shoeColors = ['Merah', 'Hijau', 'Hitam', 'Putih', 'Biru']
const shoeSizes = ['EU 38', 'EU 40', 'EU 42', 'EU 44', 'EU 46']

function gen(
  sku: string,
  dim1: string[],
  dim2: string[],
  baseDelta = 0,
  deltaStep = 0,
  baseStock = 10,
) {
  return dim1.flatMap((d1, i) =>
    dim2.map((d2, j) =>
      v(
        `${sku}-${d1.replace(/\s/g, '')}-${d2.substring(0, 3).toUpperCase()}`,
        `${d1} / ${d2}`,
        baseDelta + i * deltaStep,
        Math.max(0, baseStock - i * 2 + j),
      ),
    ),
  )
}

export const PRODUCT_CATALOG: Product[] = [
  {
    id: 'SKU-1001',
    sku: 'SKU-1001',
    name: 'Wireless Over-Ear Headphones',
    category_id: 'electronics',
    base_price: 149,
    stock: 120,
    rating: 4.8,
    review_count: 342,
    cover_image_url: img('photo-1505740420928-5e560c06d30e'),
    is_featured: true,
    discount_percent: 10,
    badge: 'SALE',
    summary:
      'Studio-tuned wireless headphones with active noise cancelling, 30-hour battery life and plush memory-foam ear cushions.',
    specs: [
      { spec_name: 'Driver', spec_value: '40 mm dynamic' },
      { spec_name: 'Battery', spec_value: 'Up to 30 hours' },
      { spec_name: 'Bluetooth', spec_value: '5.3, multipoint' },
      { spec_name: 'Weight', spec_value: '254 g' },
      { spec_name: 'Includes', spec_value: 'USB-C cable, carry case' },
    ],
    variants: gen('SKU-1001', elecSizes, elecColors, 0, 2, 12),
  },
  {
    id: 'SKU-1002',
    sku: 'SKU-1002',
    name: 'Minimal Smart Watch 42mm',
    category_id: 'electronics',
    base_price: 229,
    stock: 64,
    rating: 4.6,
    review_count: 128,
    cover_image_url: img('photo-1523275335684-37898b6baf30'),
    is_featured: true,
    summary:
      'Everyday smartwatch with always-on display, heart-rate and sleep tracking, and five-day battery life.',
    specs: [
      { spec_name: 'Display', spec_value: '1.8" AMOLED, always-on' },
      { spec_name: 'Battery', spec_value: '5 days typical' },
      { spec_name: 'Water rating', spec_value: '5 ATM' },
      { spec_name: 'Sensors', spec_value: 'HR, SpO2, GPS' },
      { spec_name: 'Strap', spec_value: 'Interchangeable 22 mm' },
    ],
    variants: gen('SKU-1002', elecSizes, elecColors, 0, 3, 10),
  },
  {
    id: 'SKU-1003',
    sku: 'SKU-1003',
    name: 'Compact Mirrorless Camera',
    category_id: 'electronics',
    base_price: 649,
    stock: 18,
    rating: 4.9,
    review_count: 89,
    cover_image_url: img('photo-1526170375885-4d8ecf77b99f'),
    badge: 'NEW',
    summary:
      '24 MP mirrorless body with 4K video, in-body stabilization and a compact kit lens — ready for travel and street.',
    specs: [
      { spec_name: 'Sensor', spec_value: '24 MP APS-C' },
      { spec_name: 'Video', spec_value: '4K / 30 fps' },
      { spec_name: 'Stabilization', spec_value: '5-axis IBIS' },
      { spec_name: 'Mount', spec_value: 'Lens kit 16-50 mm' },
      { spec_name: 'Card slot', spec_value: 'SD UHS-II' },
    ],
    variants: gen('SKU-1003', elecSizes, elecColors, 0, 5, 8),
  },
  {
    id: 'SKU-1004',
    sku: 'SKU-1004',
    name: 'True Wireless Earbuds',
    category_id: 'electronics',
    base_price: 89,
    stock: 210,
    rating: 4.5,
    review_count: 210,
    discount_percent: 15,
    cover_image_url: img('photo-1600294037681-c80b4cb5b434'),
    summary:
      'Pocket-charging case, punchy bass, and crystal-clear calls with four-mic noise handling.',
    specs: [
      { spec_name: 'Playback', spec_value: '7 h + 21 h case' },
      { spec_name: 'ANC', spec_value: 'Passive seal' },
      { spec_name: 'Charging', spec_value: 'USB-C, wireless' },
      { spec_name: 'Water rating', spec_value: 'IPX4' },
      { spec_name: 'Includes', spec_value: '3 tip sizes' },
    ],
    variants: gen('SKU-1004', elecSizes, elecColors, 0, 2, 20),
  },
  {
    id: 'SKU-2001',
    sku: 'SKU-2001',
    name: 'Crew Neck Cotton Tee',
    category_id: 'apparel',
    base_price: 24,
    stock: 340,
    rating: 4.4,
    review_count: 56,
    discount_percent: 15,
    cover_image_url: img('photo-1521572163474-6864f9cf17ab'),
    is_featured: true,
    summary:
      'Heavyweight 220 gsm organic cotton tee with a clean crew neck and a fit that survives the wash cycle.',
    specs: [
      { spec_name: 'Material', spec_value: '100% organic cotton' },
      { spec_name: 'Weight', spec_value: '220 gsm' },
      { spec_name: 'Fit', spec_value: 'Regular' },
      { spec_name: 'Care', spec_value: 'Machine wash 30°C' },
      { spec_name: 'Sizes', spec_value: 'XS – XXL' },
    ],
    variants: gen('SKU-2001', apparelSizes, apparelColors, 0, 0, 18),
  },
  {
    id: 'SKU-2002',
    sku: 'SKU-2002',
    name: 'Fleece-Lined Hoodie',
    category_id: 'apparel',
    base_price: 59,
    stock: 96,
    rating: 4.7,
    review_count: 142,
    cover_image_url: img('photo-1556821840-3a63f95609a7'),
    badge: 'BEST SELLER',
    summary:
      'Brushed-back fleece hoodie with a kangaroo pocket, double-layer hood and ribbed cuffs.',
    specs: [
      { spec_name: 'Material', spec_value: '80% cotton, 20% poly' },
      { spec_name: 'Weight', spec_value: '360 gsm fleece' },
      { spec_name: 'Fit', spec_value: 'Relaxed' },
      { spec_name: 'Care', spec_value: 'Machine wash 30°C' },
      { spec_name: 'Sizes', spec_value: 'XS – XXL' },
    ],
    variants: gen('SKU-2002', apparelSizes, apparelColors, 0, 2, 14),
  },
  {
    id: 'SKU-2003',
    sku: 'SKU-2003',
    name: 'Retro Running Sneakers',
    category_id: 'apparel',
    base_price: 95,
    stock: 0,
    rating: 4.3,
    review_count: 98,
    discount_percent: 20,
    cover_image_url: img('photo-1542291026-7eec264c27ff'),
    badge: 'SALE',
    summary:
      'Suede-and-mesh retro runners with a cushioned midsole — the silhouette that never goes out of rotation.',
    specs: [
      { spec_name: 'Upper', spec_value: 'Suede + mesh' },
      { spec_name: 'Midsole', spec_value: 'EVA cushion' },
      { spec_name: 'Sizes', spec_value: '36 – 46 EU' },
      { spec_name: 'Weight', spec_value: '285 g (US 9)' },
      { spec_name: 'Care', spec_value: 'Spot clean' },
    ],
    variants: gen('SKU-2003', shoeSizes, shoeColors, 0, 2, 9),
  },
  {
    id: 'SKU-2004',
    sku: 'SKU-2004',
    name: 'Washed Denim Jacket',
    category_id: 'apparel',
    base_price: 85,
    stock: 42,
    rating: 4.5,
    review_count: 76,
    cover_image_url: img('photo-1551028719-00167b16eac5'),
    summary:
      'Classic five-pocket trucker jacket in a soft stone-washed 12 oz denim with button front.',
    specs: [
      { spec_name: 'Material', spec_value: '100% cotton denim' },
      { spec_name: 'Weight', spec_value: '12 oz' },
      { spec_name: 'Fit', spec_value: 'True to size' },
      { spec_name: 'Care', spec_value: 'Machine wash 30°C' },
      { spec_name: 'Sizes', spec_value: 'S – XXL' },
    ],
    variants: gen('SKU-2004', apparelSizes, apparelColors, 0, 0, 12),
  },
  {
    id: 'SKU-3001',
    sku: 'SKU-3001',
    name: 'Three-Seater Fabric Sofa',
    category_id: 'home-living',
    base_price: 899,
    stock: 0,
    rating: 4.8,
    review_count: 203,
    cover_image_url: img('photo-1555041469-a586c61ea9bc'),
    is_featured: true,
    is_preorder: true,
    preorder_eta: new Date(Date.now() + 21 * 86400000).toISOString(),
    preorder_deposit: 99,
    badge: 'BEST SELLER',
    summary:
      'Mid-century inspired three-seater in performance fabric with removable, machine-washable covers.',
    specs: [
      { spec_name: 'Dimensions', spec_value: '206 × 88 × 84 cm' },
      { spec_name: 'Material', spec_value: 'Performance fabric' },
      { spec_name: 'Covers', spec_value: 'Removable, washable' },
      { spec_name: 'Frame', spec_value: 'Kiln-dried hardwood' },
      { spec_name: 'Assembly', spec_value: 'None — ships assembled' },
    ],
    variants: gen('SKU-3001', ['Grey', 'Beige', 'Navy', 'Green', 'Charcoal'], ['Linen', 'Velvet', 'Canvas', 'Wool', 'Suede'], 0, 10, 8),
  },
  {
    id: 'SKU-3002',
    sku: 'SKU-3002',
    name: 'Arched Floor Lamp',
    category_id: 'home-living',
    base_price: 129,
    stock: 55,
    rating: 4.6,
    review_count: 44,
    discount_percent: 12,
    cover_image_url: img('photo-1507473885765-e6ed057f782c'),
    summary:
      'Powder-coated steel floor lamp with a warm dimmable LED head — sculptural light for any corner.',
    specs: [
      { spec_name: 'Height', spec_value: '168 cm' },
      { spec_name: 'Bulb', spec_value: 'Integrated LED, dimmable' },
      { spec_name: 'Colour temp', spec_value: '2700 K' },
      { spec_name: 'Material', spec_value: 'Steel, matte black' },
      { spec_name: 'Cable', spec_value: '2.5 m, in-line switch' },
    ],
    variants: gen('SKU-3002', ['Matte Black', 'Brass', 'Chrome', 'Copper', 'White'], ['Warm', 'Cool', 'Daylight', 'Dim', 'Bright'], 0, 5, 12),
  },
  {
    id: 'SKU-3003',
    sku: 'SKU-3003',
    name: 'Linen Bedding Set — Queen',
    category_id: 'home-living',
    base_price: 139,
    stock: 31,
    rating: 4.9,
    review_count: 67,
    discount_percent: 18,
    cover_image_url: img('photo-1505693416388-ac5ce068fe85'),
    badge: 'SALE',
    summary:
      'Stone-washed pure linen duvet cover and two pillowcases — breathable, gets softer with every wash.',
    specs: [
      { spec_name: 'Material', spec_value: '100% French flax linen' },
      { spec_name: 'Size', spec_value: 'Queen (220 × 240 cm)' },
      { spec_name: 'Pieces', spec_value: 'Duvet cover + 2 cases' },
      { spec_name: 'Closure', spec_value: 'Horn-look buttons' },
      { spec_name: 'Care', spec_value: 'Machine wash 40°C' },
    ],
    variants: gen('SKU-3003', ['Single', 'Queen', 'King', 'Super King', 'Custom'], ['Putih', 'Beige', 'Abu', 'Sage', 'Blush'], 0, 15, 9),
  },
  {
    id: 'SKU-3004',
    sku: 'SKU-3004',
    name: 'Stainless Cookware Set 5pc',
    category_id: 'home-living',
    base_price: 179,
    stock: 26,
    rating: 4.4,
    review_count: 31,
    cover_image_url: img('photo-1556911220-bff31c812dba'),
    summary:
      'Tri-ply stainless cookware set — fry pan, saucepans and stockpot with heatproof handles and lids.',
    specs: [
      { spec_name: 'Core', spec_value: 'Tri-ply, 3 mm' },
      { spec_name: 'Pieces', spec_value: '5 + glass lids' },
      { spec_name: 'Oven safe', spec_value: 'Up to 260°C' },
      { spec_name: 'Dishwasher', spec_value: 'Safe' },
      { spec_name: 'Warranty', spec_value: 'Lifetime' },
    ],
    variants: gen('SKU-3004', ['Silver', 'Black', 'Gold', 'Copper', 'Gunmetal'], ['Standard', 'Nonstick', 'Ceramic', 'Cast Iron', 'Hammered'], 0, 8, 10),
  },
  {
    id: 'SKU-4001',
    sku: 'SKU-4001',
    name: 'Laptop Backpack 28L',
    category_id: 'accessories',
    base_price: 79,
    stock: 140,
    rating: 4.7,
    review_count: 189,
    discount_percent: 20,
    cover_image_url: img('photo-1553062407-98eeb64c6a62'),
    is_featured: true,
    summary:
      'Weatherproof roll-top backpack with padded 16" laptop sleeve, external bottle pocket and hidden stash slot.',
    specs: [
      { spec_name: 'Capacity', spec_value: '28 L' },
      { spec_name: 'Laptop', spec_value: 'Up to 16"' },
      { spec_name: 'Material', spec_value: '900D coated nylon' },
      { spec_name: 'Pockets', spec_value: '5 internal, 2 external' },
      { spec_name: 'Weight', spec_value: '980 g' },
    ],
    variants: gen('SKU-4001', apparelSizes, ['Hitam', 'Abu', 'Navy', 'Olive', 'Tan'], 0, 0, 16),
  },
  {
    id: 'SKU-4002',
    sku: 'SKU-4002',
    name: 'Polarized Aviator Sunglasses',
    category_id: 'accessories',
    base_price: 68,
    stock: 88,
    rating: 4.5,
    review_count: 95,
    cover_image_url: img('photo-1511499767150-a48a237f0083'),
    summary:
      'Classic aviators with polarized scratch-resistant lenses and a lightweight stainless frame.',
    specs: [
      { spec_name: 'Lens', spec_value: 'Polarized, UV400' },
      { spec_name: 'Frame', spec_value: 'Stainless steel' },
      { spec_name: 'Width', spec_value: '58 mm' },
      { spec_name: 'Includes', spec_value: 'Hard case, cloth' },
      { spec_name: 'Care', spec_value: 'Microfibre clean' },
    ],
    variants: gen('SKU-4002', ['54mm', '56mm', '58mm', '60mm', '62mm'], ['Hitam', 'Gold', 'Silver', 'Rose Gold', 'Gunmetal'], 0, 2, 12),
  },
  {
    id: 'SKU-4003',
    sku: 'SKU-4003',
    name: 'Full-Grain Leather Tote',
    category_id: 'accessories',
    base_price: 149,
    stock: 39,
    rating: 4.8,
    review_count: 112,
    discount_percent: 25,
    cover_image_url: img('photo-1584917865442-de89df76afd3'),
    badge: 'SALE',
    summary:
      'Structured tote in vegetable-tanned full-grain leather with an interior zip pocket and brass hardware.',
    specs: [
      { spec_name: 'Material', spec_value: 'Full-grain leather' },
      { spec_name: 'Dimensions', spec_value: '38 × 30 × 14 cm' },
      { spec_name: 'Lining', spec_value: 'Cotton canvas' },
      { spec_name: 'Hardware', spec_value: 'Solid brass' },
      { spec_name: 'Warranty', spec_value: '10 years' },
    ],
    variants: gen('SKU-4003', apparelSizes, ['Coklat', 'Hitam', 'Tan', 'Cognac', 'Olive'], 0, 5, 9),
  },
  {
    id: 'SKU-5001',
    sku: 'SKU-5001',
    name: '4-Person Camping Tent',
    category_id: 'outdoors',
    base_price: 219,
    stock: 0,
    rating: 4.6,
    review_count: 78,
    cover_image_url: img('photo-1478131143081-80f7f84ca84d'),
    is_featured: true,
    is_preorder: true,
    preorder_eta: new Date(Date.now() + 14 * 86400000).toISOString(),
    preorder_deposit: 49,
    badge: 'BEST SELLER',
    summary:
      'Waterproof dome tent with a roomy 4-person floor, dual vestibules and a 10-minute pitch with color-coded poles.',
    specs: [
      { spec_name: 'Capacity', spec_value: '4 people' },
      { spec_name: 'Floor', spec_value: '240 × 240 cm' },
      { spec_name: 'Rainfly', spec_value: '3000 mm PU' },
      { spec_name: 'Weight', spec_value: '4.9 kg' },
      { spec_name: 'Pitch time', spec_value: '~10 minutes' },
    ],
    variants: gen('SKU-5001', ['2P', '3P', '4P', '6P', '8P'], ['Hijau', 'Biru', 'Oranye', 'Abu', 'Merah'], 0, 15, 7),
  },
  {
    id: 'SKU-5002',
    sku: 'SKU-5002',
    name: 'Insulated Steel Bottle 750ml',
    category_id: 'outdoors',
    base_price: 32,
    stock: 260,
    rating: 4.9,
    review_count: 240,
    discount_percent: 30,
    badge: 'SALE',
    cover_image_url: img('photo-1602143407151-7111542de6e8'),
    summary:
      'Double-wall vacuum bottle that keeps drinks cold 24 h or hot 12 h. Leakproof lid, powder-coat finish.',
    specs: [
      { spec_name: 'Capacity', spec_value: '750 ml' },
      { spec_name: 'Insulation', spec_value: 'Double-wall vacuum' },
      { spec_name: 'Cold / hot', spec_value: '24 h / 12 h' },
      { spec_name: 'Material', spec_value: '18/8 stainless steel' },
      { spec_name: 'Lid', spec_value: 'Leakproof twist cap' },
    ],
    variants: gen('SKU-5002', ['350ml', '500ml', '750ml', '1L', '1.5L'], ['Black', 'Steel', 'Moss', 'Navy', 'Sand'], 0, 3, 15),
  },
  {
    id: 'SKU-5003',
    sku: 'SKU-5003',
    name: 'Rechargeable Camping Lantern',
    category_id: 'outdoors',
    base_price: 45,
    stock: 73,
    rating: 4.7,
    review_count: 54,
    cover_image_url: img('photo-1571508601891-ca5e7a713859'),
    badge: 'NEW',
    summary:
      'Collapsible lantern with 360° warm light, four brightness levels and a USB-C rechargeable battery.',
    specs: [
      { spec_name: 'Brightness', spec_value: 'Up to 500 lm' },
      { spec_name: 'Runtime', spec_value: '6 – 60 h' },
      { spec_name: 'Charging', spec_value: 'USB-C, 3 h' },
      { spec_name: 'Water rating', spec_value: 'IPX4' },
      { spec_name: 'Weight', spec_value: '290 g' },
    ],
    variants: gen('SKU-5003', ['Mini', 'S', 'M', 'L', 'XL'], ['Warm', 'Cool', 'Daylight', 'Amber', 'Red'], 0, 2, 12),
  },
]
