export { WishlistButton } from './components/WishlistButton'
export { useWishlist, useWishlistStore } from './hooks/useWishlist'
export { useWishlistCatalog } from './hooks/useWishlistCatalog'
export { wishlistService } from './services/wishlist.service'
export type { WishlistItem } from './types/wishlist.type'
